services:
    postgres:
        image: postgres:14.2
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
            #- ./postgres/pg_data:/var/lib/postgresql/data/
        env_file:
             - .env
        # restart: always
    jupyter-local:
        build: ./jupyter-local
        ports:
        - 8888:8888
        - 4040:4040
        - 4041:4041
        links:
        - postgres
        volumes:
        - ./jupyter-local/notebooks:/home/jovyan/work
        - ./src:/home/jovyan/work/src
        - ./jars:/home/jovyan/work/jars
        - ./data:/home/jovyan/work/data
    vertica:
        image: dataplatform/docker-vertica
        ports:
            - 5433:5433
        volumes:
            - ./data/:/tmp/input
    vertica-init:
        build: ./vertica
        links:
        - vertica

    # adminer:
    #     image: adminer
    #     ports:
    #         - "8080:8080"
    #     restart: always

